// Embeds PDF.js (legacy build) as strings so the app can read PDF statements offline
// inside a WebView. Runs on postinstall; output is git-ignored.
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'node_modules', 'pdfjs-dist', 'legacy', 'build');
const out = path.join(__dirname, '..', 'src', 'generated', 'pdfjs.ts');
// Keep "</script" from closing the inline <script> tag it is placed in.
const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/<\/script/gi, '<\\/script');

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  '// Generated by scripts/gen-pdfjs.js — do not edit.\n' +
    `export const PDFJS_LIB: string = ${JSON.stringify(read('pdf.min.js'))};\n` +
    `export const PDFJS_WORKER: string = ${JSON.stringify(read('pdf.worker.min.js'))};\n`,
);
console.log('pdfjs embedded →', path.relative(process.cwd(), out));
